CREATE TABLE route (
    route_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_hub_id bigint NOT NULL,
    dest_hub_id bigint NOT NULL,
    mode text NOT NULL,
    distance_km numeric(10,2) NOT NULL,
    planned_hours numeric(8,2) NOT NULL,
    CONSTRAINT uq_route_origin_dest_mode UNIQUE (origin_hub_id, dest_hub_id, mode),
    CONSTRAINT fk_route_origin_hub FOREIGN KEY (origin_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_route_dest_hub FOREIGN KEY (dest_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT check_route_origin_neq_dest CHECK (origin_hub_id <> dest_hub_id),
    CONSTRAINT check_distance_km_positive CHECK (distance_km > 0),
    CONSTRAINT check_planned_hours_positive CHECK (planned_hours > 0)
);

CREATE TABLE package (
    package_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_no text NOT NULL CONSTRAINT package_tracking_no_key UNIQUE,
    sender_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    service_id bigint NOT NULL,
    weight_kg numeric(10,2) NOT NULL,
    length_cm numeric(10,2),
    width_cm numeric(10,2),
    height_cm numeric(10,2),
    shipping_fee numeric(12,2),
    origin_hub_id bigint NOT NULL,
    dest_hub_id bigint NOT NULL,
    current_status text NOT NULL,
    CONSTRAINT fk_package_sender FOREIGN KEY (sender_id) REFERENCES customer(customer_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_package_receiver FOREIGN KEY (receiver_id) REFERENCES customer(customer_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_package_service FOREIGN KEY (service_id) REFERENCES service_type(service_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_package_origin_hub FOREIGN KEY (origin_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_package_dest_hub FOREIGN KEY (dest_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_package_current_status FOREIGN KEY (current_status) REFERENCES status_code(status_code) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT check_package_sender_neq_receiver CHECK (sender_id <> receiver_id),
    CONSTRAINT check_package_weight_kg_positive CHECK (weight_kg > 0),
    CONSTRAINT check_package_length_cm_positive CHECK (length_cm IS NULL OR length_cm > 0),
    CONSTRAINT check_package_width_cm_positive CHECK (width_cm IS NULL OR width_cm > 0),
    CONSTRAINT check_package_height_cm_positive CHECK (height_cm IS NULL OR height_cm > 0),
    CONSTRAINT check_package_shipping_fee_non_negative CHECK (shipping_fee IS NULL OR shipping_fee >= 0)
);

CREATE TABLE tracking_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id bigint NOT NULL,
    hub_id bigint NOT NULL,
    status_code text NOT NULL,
    event_time timestamptz NOT NULL,
    recorded_by bigint,
    CONSTRAINT uq_tracking_event_package_time UNIQUE (package_id, event_time),
    CONSTRAINT fk_tracking_event_package FOREIGN KEY (package_id) REFERENCES package(package_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_tracking_event_hub FOREIGN KEY (hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_tracking_event_status FOREIGN KEY (status_code) REFERENCES status_code(status_code) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_tracking_event_recorded_by FOREIGN KEY (recorded_by) REFERENCES staff(staff_id) ON UPDATE NO ACTION ON DELETE RESTRICT
);
