CREATE TABLE customer (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    phone text NOT NULL CONSTRAINT customer_phone_key UNIQUE,
    email text NOT NULL CONSTRAINT customer_email_key UNIQUE
);

CREATE TABLE staff (
    staff_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    hub_id bigint NOT NULL,
    CONSTRAINT fk_staff_hub FOREIGN KEY (hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE driver (
    driver_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    license_no text NOT NULL CONSTRAINT driver_license_no_key UNIQUE,
    phone text NOT NULL CONSTRAINT driver_phone_key UNIQUE,
    base_hub_id bigint NOT NULL,
    CONSTRAINT fk_driver_base_hub FOREIGN KEY (base_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE vehicle (
    vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_no text NOT NULL CONSTRAINT vehicle_plate_no_key UNIQUE,
    vehicle_type text NOT NULL,
    capacity_kg numeric(10,2) NOT NULL,
    home_hub_id bigint NOT NULL,
    CONSTRAINT check_capacity_kg_positive CHECK (capacity_kg > 0),
    CONSTRAINT fk_vehicle_home_hub FOREIGN KEY (home_hub_id) REFERENCES transit_hub(hub_id) ON UPDATE NO ACTION ON DELETE RESTRICT
);
