CREATE TABLE status_code (
    status_code text PRIMARY KEY,
    status_name text NOT NULL CONSTRAINT status_code_status_name_key UNIQUE,
    sequence_no integer NOT NULL CONSTRAINT status_code_sequence_no_key UNIQUE,
    is_terminal boolean NOT NULL DEFAULT false,
    CONSTRAINT check_sequence_no_positive CHECK (sequence_no > 0)
);

CREATE TABLE service_type (
    service_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name text NOT NULL CONSTRAINT service_type_service_name_key UNIQUE,
    base_rate numeric(12,2) NOT NULL,
    per_kg_rate numeric(12,2) NOT NULL,
    sla_hours integer NOT NULL,
    max_weight_kg numeric(10,2) NOT NULL,
    CONSTRAINT check_base_rate_non_negative CHECK (base_rate >= 0),
    CONSTRAINT check_per_kg_rate_non_negative CHECK (per_kg_rate >= 0),
    CONSTRAINT check_sla_hours_positive CHECK (sla_hours > 0),
    CONSTRAINT check_max_weight_kg_positive CHECK (max_weight_kg > 0)
);

CREATE TABLE transit_hub (
    hub_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_code text NOT NULL CONSTRAINT transit_hub_hub_code_key UNIQUE,
    hub_name text NOT NULL
);
