CREATE TABLE trip (
    trip_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    driver_id bigint NOT NULL,
    depart timestamptz NOT NULL,
    CONSTRAINT uq_trip_vehicle_depart UNIQUE (vehicle_id, depart),
    CONSTRAINT uq_trip_driver_depart UNIQUE (driver_id, depart),
    CONSTRAINT fk_trip_route FOREIGN KEY (route_id) REFERENCES route(route_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_trip_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle(vehicle_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_trip_driver FOREIGN KEY (driver_id) REFERENCES driver(driver_id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE package_leg (
    trip_id bigint NOT NULL,
    package_id bigint NOT NULL,
    loaded_at timestamptz,
    unloaded_at timestamptz,
    PRIMARY KEY (trip_id, package_id),
    CONSTRAINT fk_package_leg_trip FOREIGN KEY (trip_id) REFERENCES trip(trip_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT fk_package_leg_package FOREIGN KEY (package_id) REFERENCES package(package_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT check_package_leg_times CHECK (
        unloaded_at IS NULL 
        OR loaded_at IS NULL 
        OR unloaded_at >= loaded_at
    )
);

CREATE TABLE delivery_attempt (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id bigint NOT NULL,
    driver_id bigint NOT NULL,
    attempt_time timestamptz NOT NULL,
    outcome text NOT NULL,
    failure_reason text,
    CONSTRAINT uq_delivery_attempt_package_time UNIQUE (package_id, attempt_time),
    CONSTRAINT fk_delivery_attempt_package FOREIGN KEY (package_id) REFERENCES package(package_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT fk_delivery_attempt_driver FOREIGN KEY (driver_id) REFERENCES driver(driver_id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT check_delivery_attempt_outcome_values CHECK (outcome IN ('SUCCESS', 'FAILED')),
    CONSTRAINT check_delivery_attempt_reason_consistency CHECK (
        (outcome = 'FAILED' AND failure_reason IS NOT NULL AND btrim(failure_reason) <> '')
        OR
        (outcome = 'SUCCESS' AND failure_reason IS NULL)
    )
);
